    - name: Install Git
      apt:
        name: git
        update_cache: yes

    - name: Clone the Git repository
      git:
        repo: https://github.com/binayapuri/sample_todo.git
        dest: /var/www/html/

    - name: Install dependencies
      command: npm install
      args:
        chdir: /var/www/html/

    - name: Install a compatible version of Node.js
      shell: npm install -g n && n 14
      args:
        creates: /usr/local/bin/node14


    - name: Run Express app
      command: node server.js
      args:
        chdir: /var/www/html/